### ISSUE TITLE
Workflow API cannot get Activities metadata from UnifiedViews

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/workflow-component#36]
#### Description
The wfAPI cannot retrieve Activities metadata from UnifiedViews. The response from server is: 
```
{
  "status": 500,
  "type": "about:blank",
  "detail": "<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>",
  "title": "Internal Server Error"
}
```
The wfAPI does not show any issue in the logs.
#### DoD

- [x] Investigate Bug and fix if can be replicated.
- [x] Add Unit tests for the identified issues.

#### Testing
Peer review

**Comment by jkesanie** [comment]
```
wfapi_1          | Traceback (most recent call last):
wfapi_1          |   File "/root/.pex/install/Flask-0.10.1-py2-none-any.whl.4b4cd0f3a4c0d9b3974369d6d12dbe9bdc31ab75/Flask-0.10.1-py2-none-any.whl/flask/app.py", line 1817, in wsgi_app
wfapi_1          |     response = self.full_dispatch_request()
wfapi_1          |   File "/root/.pex/install/Flask-0.10.1-py2-none-any.whl.4b4cd0f3a4c0d9b3974369d6d12dbe9bdc31ab75/Flask-0.10.1-py2-none-any.whl/flask/app.py", line 1477, in full_dispatch_request
wfapi_1          |     rv = self.handle_user_exception(e)
wfapi_1          |   File "/root/.pex/install/Flask-0.10.1-py2-none-any.whl.4b4cd0f3a4c0d9b3974369d6d12dbe9bdc31ab75/Flask-0.10.1-py2-none-any.whl/flask/app.py", line 1381, in handle_user_exception
wfapi_1          |     reraise(exc_type, exc_value, tb)
wfapi_1          |   File "/root/.pex/install/Flask-0.10.1-py2-none-any.whl.4b4cd0f3a4c0d9b3974369d6d12dbe9bdc31ab75/Flask-0.10.1-py2-none-any.whl/flask/app.py", line 1475, in full_dispatch_request
wfapi_1          |     rv = self.dispatch_request()
wfapi_1          |   File "/root/.pex/install/Flask-0.10.1-py2-none-any.whl.4b4cd0f3a4c0d9b3974369d6d12dbe9bdc31ab75/Flask-0.10.1-py2-none-any.whl/flask/app.py", line 1461, in dispatch_request
wfapi_1          |     return self.view_functions[rule.endpoint](**req.view_args)
wfapi_1          |   File "/root/.pex/install/connexion-1.0.129-py2-none-any.whl.4c5bb0f1675afb8a0040a43ecb6a9c561b52c4ea/connexion-1.0.129-py2-none-any.whl/connexion/decorators/validation.py", line 290, in wrapper
wfapi_1          |     response = function(*args, **kwargs)
wfapi_1          |   File "/root/.pex/install/connexion-1.0.129-py2-none-any.whl.4c5bb0f1675afb8a0040a43ecb6a9c561b52c4ea/connexion-1.0.129-py2-none-any.whl/connexion/decorators/parameter.py", line 156, in wrapper
wfapi_1          |     return function(*args, **kwargs)
wfapi_1          |   File "/root/.pex/install/wf_API-0.1-py2-none-any.whl.f73f47f90d57b4924ad2dbaf18448ea37afc11fc/wf_API-0.1-py2-none-any.whl/wf_api/api/activity.py", line 11, in activity_get
wfapi_1          |     data = activity_get_output('turtle', modifiedSince)
wfapi_1          |   File "/root/.pex/install/wf_API-0.1-py2-none-any.whl.f73f47f90d57b4924ad2dbaf18448ea37afc11fc/wf_API-0.1-py2-none-any.whl/wf_api/uv/activity_metadata.py", line 151, in activity_get_output
wfapi_1          |     activity_graph = data.activity(modifiedSince)
wfapi_1          |   File "/root/.pex/install/wf_API-0.1-py2-none-any.whl.f73f47f90d57b4924ad2dbaf18448ea37afc11fc/wf_API-0.1-py2-none-any.whl/wf_api/uv/activity_metadata.py", line 33, in activity
wfapi_1          |     cls.fetch_metadata(db_cursor, activity_graph, KAISA)
wfapi_1          |   File "/root/.pex/install/wf_API-0.1-py2-none-any.whl.f73f47f90d57b4924ad2dbaf18448ea37afc11fc/wf_API-0.1-py2-none-any.whl/wf_api/uv/activity_metadata.py", line 142, in fetch_metadata
wfapi_1          |     row['activityId'], namespace, graph)
wfapi_1          |   File "/root/.pex/install/wf_API-0.1-py2-none-any.whl.f73f47f90d57b4924ad2dbaf18448ea37afc11fc/wf_API-0.1-py2-none-any.whl/wf_api/uv/parse_config.py", line 12, in parse_metadata_config
wfapi_1          |     soup = BeautifulSoup(config, 'lxml-xml')
wfapi_1          |   File "/root/.pex/install/beautifulsoup4-4.5.1-py2-none-any.whl.4f69d31b34ff50f9c8307a163224a04670715c67/beautifulsoup4-4.5.1-py2-none-any.whl/bs4/__init__.py", line 165, in __init__
wfapi_1          |     % ",".join(features))
wfapi_1          | FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml-xml. Do you need to install a parser library?
frontend_1       | 15:33:53.506 [http-apr-8080-exec-2] INFO  c.c.m.x.o.f.ODCSApplicationServlet - Request (29) received
frontend_1       | 15:33:53.562 [http-apr-8080-exec-2] INFO  c.c.m.x.o.f.ODCSApplicationServlet - Request (29) finished processing in: 56 ms
frontend_1       | 15:33:57.915 [http-apr-8080-exe
```

**Comment by blankdots** [comment]
fixed by removing lxml dependency and switching to xmltodict
